In [3]:
!pip install kagglehub

Collecting kagglehub
  Downloading kagglehub-0.3.13-py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.13/site-packages (from kagglehub) (24.2)
Requirement already satisfied: pyyaml in /opt/anaconda3/lib/python3.13/site-packages (from kagglehub) (6.0.2)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.13/site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.13/site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests->kagglehub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests->kagglehub) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests->kagglehub) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests->kagglehub) (2025.11.12)
Downloading kagglehub-0.3.13-py3-none-any.whl (68 kB)
Installing collected packages: kagglehub
Successfully installed kagglehub-0.3.13

In [9]:
import pandas as pd

In [13]:
df = pd.read_csv("IRIS.csv")

### A. Display the following information:
- First 10 rows
- Shape & Data types
- Summary statistics (mean, std, min, max)

In [28]:
df.head(10)
df.shape
df.dtypes
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

### B. Select only those rows where:
- petal_length > 4.5
- species = "Iris-virginica"

In [55]:
filter_df = df[(df["petal_length"] > 4.5) & (df["species"].str.lower() == "iris-virginica")]
filter_df.head()

     sepal_length  sepal_width  petal_length  petal_width         species
100           6.3          3.3           6.0          2.5  Iris-virginica
101           5.8          2.7           5.1          1.9  Iris-virginica
102           7.1          3.0           5.9          2.1  Iris-virginica
103           6.3          2.9           5.6          1.8  Iris-virginica
104           6.5          3.0           5.8          2.2  Iris-virginica

### C. Group by species and compute:
- Average sepal_length
- Maximum petal_width
- Standard deviation of sepal_width

In [58]:
df.groupby("species").agg(
    avg_sepal_length = ("sepal_length","mean"),
    max_petal_width = ("petal_width", "max"),
    std_sepal_width = ("sepal_width","std"))

                 avg_sepal_length  max_petal_width  std_sepal_width
species
Iris-setosa                 5.006              0.6         0.381024
Iris-versicolor             5.936              1.8         0.313798
Iris-virginica              6.588              2.5         0.322497

### Create a new column: "petal_ratio" = petal_length / petal_width
- For each species, find the average petal_ratio.

In [68]:
df2 = df.copy()
df2["petal_ratio"] = df2["petal_length"]/df2["petal_width"]
df2.groupby("species")["petal_ratio"].mean()

species
Iris-setosa        7.078000
Iris-versicolor    3.242837
Iris-virginica     2.780662
Name: petal_ratio, dtype: float64